version: '3'

services:
    webapp:
        image: mvc-orm:1.0
        depends_on:
            - database

    database:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: arya12345
            MYSQL_DATABASE: middleware
        ports:
            - '3306:3306'
